---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bigwhoop-main
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43

modules:
    # Add the COPR repo that provides the Bazzite kernel

  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - steam
        - docker
        - distrobox
        - headsetcontrol
        - mangohud
        - gamescope
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - gnome-software
        - toolbox

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - com.discordapp.Discord
          - io.github.kolunmi.Bazaar
          - com.github.tchx84.Flatseal
          - com.heroicgameslauncher.hgl
          - net.lutris.Lutris
          - com.usebottles.bottles
          - org.gnome.baobab
          - com.visualstudio.code
          - org.freedesktop.Platform.ffmpeg-full
          - org.mozilla.firefox
          - com.ranfdev.DistroShelf
          - org.gnome.Firmware
          - org.gnome.Weather
          - org.gnome.Calendar
          - org.gnome.Evolution
          - org.gnome.Loupe
       - scope: user # Also add Flathub user repo, but no user packages
        
  - type: gnome-extensions
    install:
        - 517
        - 3193 # Notice how extension is named "Blur my Shell" & not "Blur My Shell"?
        # Name is case-sensitive, so check if extension name is typed correctly
        - 615
        - 307 # Dash-to-Dock
        - 4222
        - 7065
        # https://extensions.gnome.org/extension/307/dash-to-dock/
        # You can also specify PK ID number from the extension URL,
        # if you encounter the scenario where there are multiple extensions with the same name.
            # You don't need to look & search for this scenario, since module will automatically fail & inform you to put PK ID number instead
            
  - type: brew
    nofile-limits: true
    brew-analytics: false

  - type: systemd
    system:
      enabled:
        - docker.service

  - type: signing
  
