---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bigwhoop-main
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - steam
        - docker
        - distrobox
        - headsetcontrol
        - mangohud
        - gamescope
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - gnome-software
        - toolbox
        
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.discordapp.Discord
          - io.github.kolunmi.Bazaar
          - com.github.tchx84.Flatseal
          - com.heroicgameslauncher.hgl
          - net.lutris.Lutris
          - com.usebottles.bottles
          - org.gnome.baobab
          - com.visualstudio.code
          - org.freedesktop.Platform.ffmpeg-full
          - org.mozilla.firefox
          - com.ranfdev.DistroShelf
          - org.gnome.Firmware
          - org.gnome.Calendar
          - org.gnome.Loupe
          - org.gnome.Evolution
      - scope: user # Also add Flathub user repo, but no user packages
      
  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry
    
  - type: gnome-extensions
    install:
      - 7065
      - 517
      - 4222
      - 615
      - 3193
      
  - type: systemd
    # this example disables automatic flatpak updates and enables a custom service unit for all users
    system:
      enabled:
        - docker.service

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
  
