---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bigwhoop-main
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 43

modules:
    # Add the COPR repo that provides the Bazzite kernel

  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
        - steam
        - gnome-disk-utility
        - docker
        - distrobox
        - headsetcontrol
        - mangohud
        - gamescope
        - rclone
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - plasma-discover
        - toolbox

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - app.zen_browser.zen
          - com.discordapp.Discord
          - io.github.kolunmi.Bazaar
          - com.github.tchx84.Flatseal
          - com.heroicgameslauncher.hgl
          - net.lutris.Lutris
          - com.usebottles.bottles
          - org.gnome.baobab
          - com.visualstudio.code
          - org.freedesktop.Platform.ffmpeg-full
          - org.mozilla.firefox
          - com.ranfdev.DistroShelf
          - org.gnome.Firmware
      - scope: user

  - type: brew
    nofile-limits: true
    brew-analytics: false

  - type: systemd
    system:
      enabled:
        - docker.service

  - type: signing
  
